export const FACILITIES = [
  {
    id: 'f1',
    name: 'Malabe Campus Main Ground',
    type: 'Outdoor Ground',
    capacity: '1000+',
    img: 'https://images.unsplash.com/photo-1577223625816-7546f13df25d?auto=format&fit=crop&q=80&w=800',
    status: 'Available',
    location: 'SLIIT ',
    hours: '8AM - 6PM',
    description: 'Premier outdoor sports facility suitable for cricket, football, and athletics events.',
  },
  {
    id: 'f2',
    name: 'Indoor Basketball Court',
    type: 'Indoor Court',
    capacity: '200',
    img: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&q=80&w=800',
    status: 'Booked',
    location: 'NSBM',
    hours: '8AM - 6PM',
    description: 'Professional grade hardwood court with premium lighting and spectator seating.',
  },
  {
    id: 'f3',
    name: 'Swimming Pool',
    type: 'Aquatics',
    capacity: '50',
    img: 'https://images.unsplash.com/photo-1576610616656-d3aa5d1f4534?auto=format&fit=crop&q=80&w=800',
    status: 'Maintenance',
    location: 'NSBM',
    hours: '8AM - 6PM',
    description: 'Olympic-sized heated swimming pool with diving boards and changing facilities.',
  },
];
